source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'mysql2', github: 'brianmario/mysql2'
gem 'mysql2-cs-bind', github: 'kamipo/mysql2-cs-bind', branch: 'perf'
gem 'jwt'


group :development do
  gem 'sinatra-contrib'
end

gem 'newrelic_rpm', require: false
gem 'oj'
